import Head from "next/head";
import Banner from "../components/Home/Banner";
import LatestShows from "../components/Home/LatestShows";

export default function Home() {
  return (
    <>
      <Head>
        <title>TVmaze - All shows</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.ico" />
      </Head>
      <main>
        <Banner />
        <LatestShows />
      </main>
    </>
  );
}
